### ISSUE TITLE
New feature: streaming video

### ISSUE THREAD

**Issue by MasterPIC** [petrj/DVBTTelevizor#35]
Hi Petr,

what about adding the ability to stream video on lan?
By remote control I see the ability to play TV channels also remotely by VPN...

Thanks again
Armando

**Comment by petrj** [comment]
Hello Armando,

Good idea, it's not difficult to stream video on LAN, but I have no plan to implement it now. Primary purpose of this app is to watch TV without internet only with your phone. If you watch TV home on LAN, you can use streaming features of Android phones (Smart view/Google cast....) 

Petr
