### ISSUE TITLE
Do you plan to build a version for AndroidTV in the future?  .

### ISSUE THREAD

**Issue by dnmnhat** [petrj/DVBTTelevizor#36]
Do you plan to build a version for AndroidTV ( Android TV Box ) in the future?  .

**Comment by petrj** [comment]
Yes, but there must be DVB-T Driver build for Android TV first.

**Comment by dnmnhat** [comment]
"DVB-T Driver": (https://play.google.com/store/apps/details?id=info.martinmarinov.dvbdriver)
I have installed DVB-T Driver + USB stick DVB ( MyGica T230 DVB-T / T2 / C ) it works well on my AndroidTV box

**Comment by petrj** [comment]
Really? I don't have Android TV device right now to check it. Could you try to install latest apk (https://github.com/petrj/DVBTTelevizor/releases) to Android TV manually please?

**Comment by petrj** [comment]
I've borrowed Android TV (NVIDIA SHIELD) and made some program modifications. MyGica T230C really works without any problem. Latest build (version 20) has Android TV support now, even recording and remote access.
